spring:
  datasource:
    username: root
    password: ggsxb
    url: jdbc:mysql://192.168.235.132:3306/gulimall_ums
    driver-class-name: com.mysql.cj.jdbc.Driver

  cloud:
    nacos:
      discover:
        server-addr: 127.0.0.1:8848

  application:
    name: gulimall-member

mybatis-plus:
  mapper-location: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto

server:
  port: 8000